### PR TITLE
Remove port mapping when rm with -f issued

### LINKED ISSUE #3358: Rancher Desktop Guest Agent is leaving behind port mappings when Docker backend is used
When users remove a container using `-f` flag, e.g `docker rm -f [CONTAINERID]`, the rancher desktop guest agent leaves behind the port mapping and fails to remove it.

### PR DESCRIPTION
**Pull request by Nino-K**
Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/3358

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

### CODE REVIEW

File: pkg/docker/events.go [hunk 1]
```diff
@@ -63,7 +65,8 @@ func (e *EventMonitor) MonitorPorts(ctx context.Context) {
 	msgCh, errCh := e.dockerClient.Events(ctx, types.EventsOptions{Filters: filters.NewArgs(
 		filters.Arg("type", "container"),
 		filters.Arg("event", startEvent),
-		filters.Arg("event", stopEvent))})
+		filters.Arg("event", stopEvent),
+		filters.Arg("event", dieEvent))})
```
Comment (mook-as) [inline pkg/docker/events.go]: Would it make sense to put the `)})` on the next line?

**Review by mook-as — APPROVED** [review]
