### PR TITLE
Fixes port binding to localhost when moby used

### LINKED ISSUE #5396: Container running on Localhost cannot be accessed with experimental tunnel and Moby engine in WSL2
### Actual Behavior

When using the experimental tunnel feature and the Moby engine with WSL2, containers running on localhost with WSL cannot be accessed on the host machine or via browser.

### Steps to Reproduce

Use Moby container engine.
Run container on localhost or 127.0.0.1.
Use experimental tunnel feature on WSL2.
Try to access the running container from browser localhost with the port.

### Result

The running container cannot be accessed from a browser or the host machine.

### Expected Behavior

The running container should be able to be accessed from a browser or the host machine.

### Additional Information

_No response_

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Cisco AnyConnect, Zscaler, Microsoft Defender and Symantec Endpoint Protection

### PR DESCRIPTION
**Pull request by Nino-K**
When using moby backend engine and the namespaced network, port binding to localhost failed. This change creates an additional iptables rule that allows container's exposed port to be discoverable in the namespaced network.

Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/5396

### CODE REVIEW

File: pkg/docker/events.go [hunk 1]
```diff
@@ -193,3 +204,43 @@ func validatePortMapping(portMap nat.PortMap) {
...
+// We enter the following rule after the existing rule:
+// DNAT       tcp  --  anywhere             anywhere             tcp dpt:9119 to:10.4.0.22:80.
+func createLoopbackIPtablesRules(containerIP string, portMappings nat.PortMap) error {
+	var errs []error
+
+	for portProto, portBindings := range portMappings {
+		for _, portBinding := range portBindings {
+			if portBinding.HostIP == "127.0.0.1" {
+				//nolint:gosec // no security concern with the potentially tainted command arguments
+				iptableCmd := exec.Command("iptables",
```
Comment (mook-as) [inline pkg/docker/events.go:226]: Perhaps we should fork `github.com/lima-vm/lima/pkg/guestagent/iptables` (which we already use) or push something upstream to do this for us?

**Review by mook-as — APPROVED** [review]
Seems to work with some light testing.
