### PR TITLE
Fixes the wrong use of k8s client-go

### LINKED ISSUE #6809: Windows guestAgent does not pick up ports from services during the initialization
Currently, guest agents fail to pick up the ports from services during the initialization. Below is a sample of the logs from guest agent after the Rancher Desktop restart:

```
2024/05/02 08:27:46 [INFO]    Starting Rancher Desktop Agent in [AdminInstall=true] mode
2024/05/02 08:27:46 [DEBUG]   kubernetes: loaded kubeconfig /etc/rancher/k3s/k3s.yaml
2024/05/02 08:27:46 [DEBUG]   watching kubernetes services
W0502 08:27:46.102384     255 reflector.go:424] k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial2024/05/02 08:27:46 [DEBUG]   kubernetes: error watching [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: network i2024/05/02 08:27:46 [ERROR]   kubernetes: unexpected error watching [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connectW0502 08:27:47.388036     255 reflector.go:424] k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial2024/05/02 08:27:47 [DEBUG]   kubernetes: error watching [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: connectio2024/05/02 08:27:47 [DEBUG]   kubernetes: got error, rolling back [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect:
2024/05/02 08:27:48 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:49 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:50 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:51 [DEBUG]   checking if container engine API is running at /var/run/docker.sock
2024/05/02 08:27:51 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:52 [DEBUG]   kubernetes: failed to read kubeconfig [error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory][con2024/05/02 08:27:53 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:54 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:55 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:56 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:57 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:58 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:27:59 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:00 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:01 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:02 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:03 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:04 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:05 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:06 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:07 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:08 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:09 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:10 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:11 [DEBUG]   kubernetes: failed to read kubeconfig [error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory][con2024/05/02 08:28:12 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:13 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:14 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:15 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k2024/05/02 08:28:16 [DEBUG]   kubernetes: loaded kubeconfig /etc/rancher/k3s/k3s.yaml
2024/05/02 08:28:16 [DEBUG]   watching kubernetes services
2024/05/02 08:28:19 [DEBUG]   received an event: {Status: start ContainerID: 0a75a9edce1728f1071db26e3c50c735b4c6279d70e4c437fd9d77a2c88ff2d2 Ports: map[]}
2024/05/02 08:28:19 [DEBUG]   received an event: {Status: start ContainerID: 09c492dba520ba655226eb0e884ae580058a1f29a154e18568c84169704b0b0f Ports: map[]}
2024/05/02 08:28:19 [DEBUG]   received an event: {Status: start ContainerID: 3253d84448d3992cbe5263932ad7d4c026231b0786009efe14d322c199b673ba Ports: map[]}
2024/05/02 08:28:19 [DEBUG]   received an event: {Status: start ContainerID: 618a0b3f23b57e7bd956795b7d0507dfc08c54363151d4b22815654d6440bb54 Ports: map[]}
2024/05/02 08:28:19 [DEBUG]   received an event: {Status: start ContainerID: f7d71f07ccbaac8dbb2ead0657facfea4e4353e2891769ce52268b0a1b50e1c3 Ports: map[]}
2024/05/02 08:28:20 [DEBUG]   received an event: {Status: start ContainerID: 46cb343cde52328a2a93baab20295503da860b826a705531605ad0c5a8d99023 Ports: map[]}
2024/05/02 08:28:20 [DEBUG]   received an event: {Status: start ContainerID: fa4e030c8afd1fbe9c487749c6289d6263dda2c65e4b14d67f022deb9a6a3cb8 Ports: map[]}
2024/05/02 08:28:20 [DEBUG]   received an event: {Status: start ContainerID: add97eea5115cf9cd67b1d4c72e4725fe1f84e582497b27847b660a92c94a4dc Ports: map[]}
2024/05/02 08:28:20 [DEBUG]   received an event: {Status: start ContainerID: c3c1f28f8c6b31ebda1b98e043b9a645fcd8016e7db52017df37b15549c365da Ports: map[]}
2024/05/02 08:28:20 [DEBUG]   received an event: {Status: start ContainerID: 20ab63c5dd89571e0b42a7911cf2970016eae646fc47179f99a7b9d5f51e9bda Ports: map[]}
2024/05/02 08:28:20 [DEBUG]   received an event: {Status: start ContainerID: 2ad95d1ca09952961e390395cd2c9f5068678612a15e41d5be8e254cd0f6a978 Ports: map[]}
2024/05/02 08:28:41 [DEBUG]   received an event: {Status: die ContainerID: fa4e030c8afd1fbe9c487749c6289d6263dda2c65e4b14d67f022deb9a6a3cb8 Ports: map[]}
2024/05/02 08:28:41 [DEBUG]   portStorage get status: map[]
2024/05/02 08:28:41 [DEBUG]   forwarding to wsl-proxy to remove port mapping: {Remove:true Ports:map[] ConnectAddrs:[]}
2024/05/02 08:28:41 [DEBUG]   portStorage remove status: map[]
2024/05/02 08:28:51 [DEBUG]   received an event: {Status: die ContainerID: 20ab63c5dd89571e0b42a7911cf2970016eae646fc47179f99a7b9d5f51e9bda Ports: map[]}
```
As you can see from the sample logs above, the traefik ports are never picked up. This could be that guest agent fails to query the K8s API for the services due to the network connectivity issue.

Potentialy fixes BATS [here](https://github.com/rancher-sandbox/rancher-desktop/pull/4972).

### PR DESCRIPTION
**Pull request by Nino-K**
Previously we were using the client incorrectly by not passing the context, this was causing internal network errors in the client due to the API server not being ready as you can see in the below logs:
```
2024/05/03 09:03:12 [DEBUG]   list of services from core v1----> []
W0503 09:03:12.649264     255 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: network is unreachable
2024/05/03 09:03:12 [DEBUG]   watching kubernetes services
2024/05/03 09:03:12 [DEBUG]   inside state watching
2024/05/03 09:03:12 [DEBUG]   kubernetes: error watching [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: network is unreachable]
2024/05/03 09:03:12 [ERROR]   kubernetes: unexpected error watching [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: network is unreachable]
W0503 09:03:14.012174     255 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: connection refused
2024/05/03 09:03:14 [DEBUG]   kubernetes: error watching [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: connection refused]
2024/05/03 09:03:14 [DEBUG]   kubernetes: got error, rolling back [error=failed to list *v1.Service: Get "https://127.0.0.1:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.0.0.1:6443: connect: connection refused]
2024/05/03 09:03:15 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
```
 However, we continued and blocked the event channel. 

With the new approach, we can determine when the API server is ready, this way we return a FATAL error and the process exists. This allows the init process to retry again until the API server becomes ready.

The below logs are for the the new approach:

```
2024/05/03 09:29:58 [INFO]    Starting Rancher Desktop Agent in [AdminInstall=true] mode
2024/05/03 09:29:58 [DEBUG]   kubernetes: loaded kubeconfig /etc/rancher/k3s/k3s.yaml
2024/05/03 09:29:58 [FATAL]   error watching services: error listing services: Get "https://127.0.0.1:6443/api/v1/services": dial tcp 127.0.0.1:6443: connect: network is unreachable
2024/05/03 09:30:03 [INFO]    Starting Rancher Desktop Agent in [AdminInstall=true] mode
2024/05/03 09:30:03 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:04 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:05 [DEBUG]   kubernetes: failed to read kubeconfig [error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory][config-path=/etc/rancher/k3s/k3s.yaml]
2024/05/03 09:30:06 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:07 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:08 [DEBUG]   checking if container engine API is running at /var/run/docker.sock
2024/05/03 09:30:08 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:09 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:10 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:11 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:12 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:13 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:14 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:15 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:16 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:17 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:18 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:19 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:20 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:21 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:22 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:23 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:24 [DEBUG]   kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]
2024/05/03 09:30:25 [DEBUG]   kubernetes: failed to read kubeconfig [error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory][config-path=/etc/rancher/k3s/k3s.yaml]
2024/05/03 09:30:26 [DEBUG]   kubernetes: loaded kubeconfig /etc/rancher/k3s/k3s.yaml
2024/05/03 09:30:26 [ERROR]   context cancellation: context canceled
2024/05/03 09:30:26 [FATAL]   error watching services: error listing services: apiserver not ready
2024/05/03 09:30:31 [INFO]    Starting Rancher Desktop Agent in [AdminInstall=true] mode
2024/05/03 09:30:31 [DEBUG]   kubernetes: loaded kubeconfig /etc/rancher/k3s/k3s.yaml
```

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/6809

### CODE REVIEW

File: pkg/kube/servicewatcher.go [hunk 1]
```diff
@@ -48,14 +48,17 @@ func watchServices(ctx context.Context, client *kubernetes.Clientset) (<-chan ev
 	informerFactory := informers.NewSharedInformerFactory(client, 1*time.Hour)
 	serviceInformer := informerFactory.Core().V1().Services()
 	sharedInformer := serviceInformer.Informer()
-	_, _ = sharedInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+	_, _ = serviceInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
```
Comment (mook-as) [inline pkg/kube/servicewatcher.go]: Is there a reason we're no longer using `sharedInformer` here? It seems to be the same thing here.

File: pkg/kube/servicewatcher.go [hunk 2]
```diff
@@ -48,14 +48,17 @@ func watchServices(ctx context.Context, client *kubernetes.Clientset) (<-chan ev
...
 		AddFunc: func(obj interface{}) {
+			log.Debugf("Service Informer: Add func called with: %+v", obj)
```
Comment (mook-as) [inline pkg/kube/servicewatcher.go:53]: Not that it matters, but these logs should be trace?

File: pkg/kube/servicewatcher.go [hunk 3]
```diff
@@ -101,15 +104,16 @@ func watchServices(ctx context.Context, client *kubernetes.Clientset) (<-chan ev
 	informerFactory.WaitForCacheSync(ctx.Done())
 	informerFactory.Start(ctx.Done())
 
-	services, err := serviceInformer.Lister().List(labels.Everything())
+	services, err := client.CoreV1().Services(corev1.NamespaceAll).List(ctx, v1.ListOptions{})
 	if err != nil {
 		return nil, nil, fmt.Errorf("error listing services: %w", err)
 	}
+	log.Debugf("coreV1 services list :%+v", services.Items)
```
Comment (mook-as) [inline pkg/kube/servicewatcher.go:111]: Same here — trace?

File: pkg/kube/servicewatcher.go [hunk 4]
```diff
@@ -101,15 +104,16 @@ func watchServices(ctx context.Context, client *kubernetes.Clientset) (<-chan ev
 	informerFactory.WaitForCacheSync(ctx.Done())
 	informerFactory.Start(ctx.Done())
 
-	services, err := serviceInformer.Lister().List(labels.Everything())
+	services, err := client.CoreV1().Services(corev1.NamespaceAll).List(ctx, v1.ListOptions{})
```
Comment (mook-as) [inline pkg/kube/servicewatcher.go:107]: Discussed with Nino: This manages to return an error (good!), but we don't handle it (bad!) and exit the whole process. At least `init` restarts us, but we should avoid needing to do that.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: pkg/kube/servicewatcher.go (hunk 2 above)
Comment (Nino-K) [reply pkg/kube/servicewatcher.go:53]: AFAIK for the trace logging to work it needs to be handled from the [main](https://github.com/rancher-sandbox/rancher-desktop-agent/blob/078aaed77ef16f0d62357340a9eb27df309df048/cmd/rancher-desktop-guestagent/main.go#L94). I don't think just changing these to trace would work 🤔 
Also, I don't recall if we handle trace logging at all in RD anywhere.

File: pkg/kube/watcher.go [hunk 5]
```diff
@@ -120,8 +122,12 @@ func WatchForServices(
 
 			eventCh, errorCh, err = watchServices(watchContext, clientset)
 			if err != nil {
-				if isTimeout(err) {
-					// If it's a time out, the server may not be running yet
+				switch {
+				case isTimeout(err):
+				case errors.Is(err, unix.ENETUNREACH):
+				case errors.Is(err, unix.ECONNREFUSED):
+				case apierrors.IsInternalError(err):
```
Comment (mook-as) [inline pkg/kube/watcher.go]: That's for _all_ internal errors; I guess that's fine?

File: pkg/kube/watcher.go [hunk 6]
```diff
@@ -258,6 +267,10 @@ func isTimeout(err error) bool {
 	return false
 }
 
+func isAPINotReady(err error) bool {
+	return strings.Contains(err.Error(), "apiserver not ready")
```
Comment (mook-as) [inline pkg/kube/watcher.go:272]: It would be good to have a comment about where this comes from (k3s, over HTTP so we can't test for a specific error object). Ideally we also check that `err` is of the right type here, but I guess that can be optional.

File: pkg/kube/watcher.go [hunk 7]
```diff
@@ -120,14 +122,21 @@ func WatchForServices(
 
 			eventCh, errorCh, err = watchServices(watchContext, clientset)
 			if err != nil {
-				if isTimeout(err) {
-					// If it's a time out, the server may not be running yet
+				switch {
+				case isTimeout(err):
+					fallthrough
```
Comment (mook-as) [inline pkg/kube/watcher.go]: This might be clearer as:
```golang
switch {
default:
  return err
case isTimeout(err):
case errors.Is(err, unix.ENETUNREACH):
case errors.Is(err, unix.ECONNREFUSED):
case isAPINotReady(err):
}
// Sleep and continue for all the expected errors
time.Sleep(time.Second)
continue
```

File: pkg/kube/servicewatcher.go (hunk 2 above)
Comment (mook-as) [reply pkg/kube/servicewatcher.go:53]: Yeah, trace would mean it's basically off and needs a code change to turn on. We don't really want to log everything in release builds (even with debug turned on).

**Review by mook-as — CHANGES_REQUESTED** [review]

File: cmd/rancher-desktop-guestagent/main.go [hunk 8]
```diff
@@ -181,7 +181,7 @@ func main() {
 			k8sServiceListenerIP := net.ParseIP(*k8sServiceListenerAddr)
 
 			if k8sServiceListenerIP == nil || !(k8sServiceListenerIP.Equal(net.IPv4zero) ||
-				k8sServiceListenerIP.Equal(net.IPv4(127, 0, 0, 1))) { //nolint:gomnd // IPv4 addr localhost
+				k8sServiceListenerIP.Equal(net.IPv4(127, 0, 0, 1))) { //nolint:gomnd,mnd // IPv4 addr localhost
```
Comment (mook-as) [inline cmd/rancher-desktop-guestagent/main.go]: It might be better to update the lint config to allow magic numbers for `net.IPv4` instead.

**Review by mook-as — APPROVED** [review]
