### PR TITLE
Fixes k8s service listener for non-admin install

### LINKED ISSUE #4124: k8s service watcher not working in non-privileged env
### Actual Behavior

The guestAgent kubernetes service watcher does no longer work correctly in non-privileged Windows environments.
If I deploy an nginx pod and a NodePort service, nginx is no longer accessible from the Windows host.

### Steps to Reproduce

- Do a non-privileged Rancher Desktop installation on Windows
- Deploy nginx pod + NodePort service
- Check if the NodePort (nginx) service is accessible on Windows

### Result

NodePort service not accessible.

### Expected Behavior

Services should be accessible from the Windows host again.

### Additional Information

_No response_

### Rancher Desktop Version

1.7.0-573-g76857559 Build of https://github.com/rancher-sandbox/rancher-desktop/suites/11430882317/artifacts/589307821

### Rancher Desktop K8s Version

1.25.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by Nino-K**
Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/4124

This will allow us to forward the port mappings to the `privilegedService` using the `portTracker` or using`listenerTracker` to start the listeners locally. Please note that I will be putting all these trackers in an interface to make the code cleaner in the future. https://github.com/rancher-sandbox/rancher-desktop-agent/issues/30

### CODE REVIEW

File: pkg/kube/servicewatcher.go [hunk 1]
```diff
@@ -153,6 +142,8 @@ func handleUpdate(oldObj, newObj interface{}, eventCh chan<- event, portTracker
 				deleted[port.Port] = port.Protocol
 			}
 		}
+
+		sendEvents(deleted, oldSvc, true, eventCh)
```
Comment (mook-as) [inline pkg/kube/servicewatcher.go]: If the port shows up in both deleted and added (i.e. it was a change unrelated to ports), we used to just skip that. Shouldn't we still do that (i.e. only call `sendEvents` after processing both sets)?

File: pkg/kube/watcher.go [hunk 2]
```diff
@@ -124,41 +132,89 @@ func WatchForServices(ctx context.Context, tracker *tcplistener.ListenerTracker,
...
+							log.Errorw("failed to delete a port from tracker", log.Fields{
+								"error":     err,
+								"UID":       event.UID,
+								"ports":     event.portMapping,
+								"namespace": event.namespace,
+								"name":      event.name,
+							})
+
+							continue
+						}
```
Comment (mook-as) [inline pkg/kube/watcher.go]: Style question: would this look better as `if err := { log.Errorw(…) } else { log.Debug(…) } continue`?

File: pkg/kube/watcher.go [hunk 3]
```diff
@@ -124,41 +132,89 @@ func WatchForServices(ctx context.Context, tracker *tcplistener.ListenerTracker,
...
+					for port := range event.portMapping {
+						if err := tracker.Remove(ctx, k8sServiceListenerIP, int(port)); err != nil {
+							log.Errorw("failed to close listener", log.Fields{
+								"error":     err,
+								"ports":     event.portMapping,
+								"namespace": event.namespace,
+								"name":      event.name,
+							})
+
+							continue
```
Comment (mook-as) [inline pkg/kube/watcher.go]: This `continue` isn't doing a whole lot (the loop continues right after anyway).

File: pkg/kube/watcher.go [hunk 4]
```diff
@@ -124,41 +132,89 @@ func WatchForServices(ctx context.Context, tracker *tcplistener.ListenerTracker,
...
+						if err != nil {
+							log.Errorw("failed to create port mapping", log.Fields{
+								"error":     err,
+								"ports":     event.portMapping,
+								"namespace": event.namespace,
+								"name":      event.name,
+							})
 
-						continue
+							continue
```
Comment (mook-as) [inline pkg/kube/watcher.go:184]: While I understand why we have the `continue` here, the end result is really weird. Would `if … { log.Errorw(…) } else if … { log.Errorw(…) } else { log.Debugf(…) }` look okay?

File: pkg/kube/watcher.go [hunk 5]
```diff
@@ -124,41 +132,89 @@ func WatchForServices(ctx context.Context, tracker *tcplistener.ListenerTracker,
...
+								"error":     err,
+								"ports":     event.portMapping,
+								"namespace": event.namespace,
+								"name":      event.name,
+							})
+
+							continue
+						}
+						log.Debugf("kubernetes service: port mapping added %s/%s:%v",
+							event.namespace, event.name, event.portMapping)
```
Comment (mook-as) [inline pkg/kube/watcher.go]: Ah, I see the trap: we do _not_ `continue` here, and continue to do the `tracker.Add` stuff right after. Which sounds unexpected…

File: pkg/kube/watcher.go [hunk 6]
```diff
@@ -46,8 +49,13 @@ const (
...
 // Any connection errors are ignored and retried.
-func WatchForServices(ctx context.Context, tracker *tcplistener.ListenerTracker, configPath string,
-	portTracker *tracker.PortTracker, k8sServiceListenerIP net.IP,
+func WatchForServices(
+	ctx context.Context,
+	configPath string,
+	k8sServiceListenerIP net.IP,
+	enablePrivilegedService bool,
+	portTracker *tracker.PortTracker,
+	tracker *tcplistener.ListenerTracker,
```
Comment (mook-as) [inline pkg/kube/watcher.go]: Please either rename `tracker` to `listenerTracker`, or rename `portTracker` to not contain `tracker`. I realize that existed before this PR, but it's just… kind of confusing to get into.

**Review by mook-as — CHANGES_REQUESTED** [review]
I expect an update to the doc comment for `PortTracker` to indicate that it's only used with the privileged service. (Also, it probably doesn't _mamanges_ the published ports…)

Also, I'm _pretty_ sure we're missing an `else` around adding ports.

File: pkg/kube/servicewatcher.go (hunk 1 above)
Comment (Nino-K) [reply pkg/kube/servicewatcher.go]: Good point, I think we should.

File: pkg/kube/watcher.go (hunk 2 above)
Comment (Nino-K) [reply pkg/kube/watcher.go]: I'm always for not using `else` as much as I can, but I can see the two `continue` after each other is not ideal either. But, in this case `else` might be cleaner. I will change we can decide then :)

File: pkg/kube/watcher.go (hunk 4 above)
Comment (Nino-K) [reply pkg/kube/watcher.go:184]: I would really want to avoid `else if` 😱 . I will be refactoring this file here: https://github.com/rancher-sandbox/rancher-desktop-agent/issues/30. This should all go away soon.

File: pkg/kube/watcher.go (hunk 5 above)
Comment (Nino-K) [reply pkg/kube/watcher.go]: Thanks, great catch!

**Review by mook-as — APPROVED** [review]
I don't love it, but with the promise of #30 I can at least live with it for now.

**Review by mook-as — APPROVED** [review]

**Comment by Nino-K** [comment]
> I don't love it, but with the promise of #30 I can at least live with it for now.

I agree, but I intentionally didn't want to make too many changes (implementing interfaces etc) just because that would require testing docker, containerd, and k8s. At this point It's best to keep the scope of changes small.
